baseURL = 'https://fediservices.nz/'
languageCode = 'en-us'
title = 'fediservices.nz'
theme = 'nightfall'

[params]
author = "FediServices.nz"
user = "info"
hostname = "fediservices.nz"

[[params.social]]
key = 0
name = "Mastodon.nz"
url = "https://mastodon.nz"

[[params.social]]
key = 1
name = "Pixelfed.nz"
url = "https://pixelfed.nz"

[[params.social]]
key = 2
name = "Calckey.nz"
url = "https://calckey.nz"

[[params.social]]
key = 3
name = "Write.nz"
url = "https://write.nz"

[[params.social]]
key = 4
name = "PeerTube.nz"
url = "https://peertube.nz"

[[params.social]]
key = 5
name = "BookWorm.nz"
url = "https://bookworm.nz"

[[params.social]]
key = 6
name = "Mtrx.nz"
url = "https://mtrx.nz"

[[params.social]]
key = 7
name = "OpenEvents.nz"
url = "https://openevents.nz"

[[params.social]]
key = 8
name = "FediRelay"
url = "https://relay.fediservices.nz"

[[params.social]]
key = 9
name = "Status"
url = "https://status.fediservices.nz"

[[params.social]]
key = 10
name = "Donate"
url = "https://donate.fediservices.nz"
